# AUTO YARD Android release şablonu — oyunun kullanmadığı motor parçaları çıkarıldı.
# Kullanım: tools/engine/build_engine.sh
production = "yes"
# -O2: resmi şablon -O3 kullanıyor; LTO ile -O3 kodu şişiriyor (.text 44 MB), -O2 hızda fark yaratmıyor.
optimize = "speed_trace"
# lto ve swappy komut satırından verilir (production onları yalnızca oradan okur); build_engine.sh: lto=full swappy=no
vulkan = "no"            # Forward+/Mobile (RenderingDevice) çizicisi; oyun gl_compatibility
module_glslang_enabled = "no"
module_betsy_enabled = "no"
module_lightmapper_rd_enabled = "no"
module_mono_enabled = "no"
disable_xr = "yes"
module_openxr_enabled = "no"
module_mobile_vr_enabled = "no"
module_webxr_enabled = "no"
disable_navigation_2d = "yes"
disable_navigation_3d = "yes"
module_navigation_2d_enabled = "no"
module_navigation_3d_enabled = "no"
disable_physics_2d = "yes"
module_godot_physics_2d_enabled = "no"
module_godot_physics_3d_enabled = "no"   # 3B fizik Jolt
module_gridmap_enabled = "no"
module_enet_enabled = "no"
module_multiplayer_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_upnp_enabled = "no"
module_jsonrpc_enabled = "no"
module_theora_enabled = "no"
module_mp3_enabled = "no"
module_interactive_music_enabled = "no"
module_noise_enabled = "no"
module_camera_enabled = "no"
module_gltf_enabled = "no"   # .glb'ler editörde .scn'e çevriliyor; çalışma anında GLTF yükleme yok
module_fbx_enabled = "no"
module_text_server_fb_enabled = "no"
module_msdfgen_enabled = "no"
module_objectdb_profiler_enabled = "no"
module_basis_universal_enabled = "no"
module_dds_enabled = "no"
module_ktx_enabled = "no"
module_tga_enabled = "no"
module_bmp_enabled = "no"
module_hdr_enabled = "no"
module_vhacd_enabled = "no"
module_visual_shader_enabled = "no"
graphite = "no"
